apiVersion: v1
kind: Service
metadata:
  name: splash
spec:
  selector:
    app: splash
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splash
  labels:
    app: splash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splash
  template:
    metadata:
      labels:
        app: splash
    spec:
      containers:
      - name: splash
        image: ghifari160/splash:0.5.0
        ports:
        - containerPort: 8080
